name: Build Plugin

on:
  push:
    branches: [ "master", "main" ]
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DALAMUD_HOME: /tmp/dalamud
      DALAMUD_ARCHIVE_URL: https://goatcorp.github.io/dalamud-distrib/latest.zip

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Set up .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 10.0.x

      - name: Cache Dalamud
        uses: actions/cache@v5
        id: cache-dalamud
        with:
          path: ${{ env.DALAMUD_HOME }}
          key: dalamud-${{ env.DALAMUD_ARCHIVE_URL }}

      - name: Download Dalamud Latest
        if: steps.cache-dalamud.outputs.cache-hit != 'true'
        run: |
          wget ${{ env.DALAMUD_ARCHIVE_URL }} -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Build Project
        run: dotnet build --configuration Release LastFmHonorific/LastFmHonorific.csproj

      - name: Upload Build Artifact (the .zip you need)
        uses: actions/upload-artifact@v7
        with:
          name: LastFmHonorific-plugin-zip
          retention-days: 30
          path: LastFmHonorific/bin/Release/LastFmHonorific/latest.zip
